platform :ios, '11.0'

target 'BellyUp' do
  # Pods for BellyUp
  pod 'React-Core', :path => '../node_modules/react-native/React'
  pod 'React-DevSupport', :path => '../node_modules/react-native/React'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/React'
  pod 'React-RCTText', :path => '../node_modules/react-native/React'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/React'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'

  use_frameworks!
end
